#!/usr/bin/env python

import argparse
import pprint
import shelve


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Prints an index file to stdout.')
    parser.add_argument(
        'index_file',
        help='Path to a file to the index')
    args = parser.parse_args()

    shelf = shelve.open(args.index_file)
    pprint.pprint(dict(shelf), indent=2)
